### ISSUE TITLE
List index out of range error

### ISSUE THREAD

**Issue by ilyassesalama** [abdulrahmanMostafa30/EgyBestBot#11]
The program is no longer working. Selecting a series doesn't do anything, and movies shows "list index out of range".

**Comment by abdelrahman30x** [comment]
EgyBest has been updated in the way ads work and some other things.
Update to <a href="https://github.com/abdulrahmanMostafa30/EgyBestBot/releases/tag/1.12">1.12</a>

**Comment by ilyassesalama** [comment]
Still not working. Now it gets stuck here.

![image](https://user-images.githubusercontent.com/46769766/197015947-68f5c2a5-9c4b-4e4b-aeb0-654a8cd86402.png)

But, after a while, the download options showed up, but the link provided is invalid. The download URL value is "None".

Also, when you specify a folder to download the movie/series, this message shows up:

![image](https://user-images.githubusercontent.com/46769766/197016579-fa7d5cb7-fead-4fc7-b7c0-05bf14aac1d8.png)

**Comment by abdelrahman30x** [comment]
Unfortunately, there are some other errors after the update from site, but I'm busy now , I will try to fix these errors as soon as possible

**Comment by abdelrahman30x** [comment]
try this <a href="https://github.com/abdulrahmanMostafa30/EgyBestBot/releases/tag/1.13">1.13</a>

**Comment by ilyassesalama** [comment]
I love how fast you're to fix bugs, good job.
