### ISSUE TITLE
Playing using external player not working

### ISSUE THREAD

**Issue by ilyassesalama** [abdulrahmanMostafa30/EgyBestBot#14]
The current option to play movies/series using external players is not working properly.

![image](https://user-images.githubusercontent.com/46769766/202832254-6442b78e-5e5f-4d8d-bfa5-77a81c918993.png)

The link used to play the video doesn't work as shown below.

![image](https://user-images.githubusercontent.com/46769766/202832173-632219a8-0da3-4450-a600-704f5ee785cf.png)

However, when you copy the video link using this option:

![image](https://user-images.githubusercontent.com/46769766/202832186-9e760eb8-2ca1-4f1d-82ec-ede3798365c9.png)

Then try to play it using VLC's "open network stream" option:

![image](https://user-images.githubusercontent.com/46769766/202832202-4e1a89bd-0ed4-48be-b849-3d4d5ee7d795.png)

The video works just fine.

![image](https://user-images.githubusercontent.com/46769766/202832235-ce5c1a43-1f41-4f68-b243-4163eb0833bd.png)

So, I think you should change the link used to play videos when selecting "Watch With an External Programs" option.

**Comment by abdelrahman30x** [comment]
" | " in URL
When passing the link with | From the VLC command line you get this error from vlc
Anyway, the problem has been fixed  <a href="https://github.com/abdulrahmanMostafa30/EgyBestBot/releases/tag/1.16">1.16</a>
