### ISSUE TITLE
Arabic is not showing correctly

### ISSUE THREAD

**Issue by ilyassesalama** [abdulrahmanMostafa30/EgyBestBot#16]
Nice feature, but the Arabic text is not showing correctly.

![image](https://user-images.githubusercontent.com/46769766/205449395-19e026c6-b321-4069-a255-3e6705bb359a.png)

Also, may I ask why the program isn't open-source? People could contribute to it including me.

**Comment by abdelrahman30x** [comment]
### **قم بالتحديث الي النسخه** <a href="https://github.com/abdulrahmanMostafa30/EgyBestBot/releases/tag/1.20">1.20</a>
انا لا اعلم ماذا تستخدم ، لكن من الواضح انه يعالج تنسيق اللغه العربيه في command line 
علي عكس windows لدي او اي شخص ، ف اللغه العربيه تكون معكوسه 
علي العموم ، أضفت خيارا لازاله عكس اللغه العربيه من الإعدادات 
قم باختيار نعم علي تعطيل عكس الكلمات
![image](https://user-images.githubusercontent.com/52821000/205489502-5207e684-245d-4040-a841-30ac628fcab8.png)

### **بخصوص السورس كود** 

شكرا علي عرضك للدعم 🖤
انت تعلم ان البرنامج استخدمه شخصيا واول نسخه منه علي شكله الحالي من 2018
الكود المصدري ليس سرا
يستطيع اي شخص ان يقوم بعمل بمثل هذا البرنامج او حتي يقوم بفك البرنامج إذا كان لديه خبره حقا !

**ما مصير البرامج المفتوحة المصدر علي GitHub الخاصه ب ايجي بيست ؟**

- لا يوجد برنامج واحد تم دعمه خلال مده كبيره ويعمل الان
-  جميع البرامج تم ايقافها او عدم تحديثها او هناك الكثير من المشاكل 
-  البرامج الي تعمل الان وهي غير مفتوحه المصدر ، تقوم باخد معلومات عن جهازك لا اعلم ماذا ياخد ويشفر :))
-  بالإضافة لان ما أفعله مخالفا لايجي بيست
-  بالإضافة أيضا بعض الناس من يريدون الكود المصدري للبرنامج ، اعلم ان لهم اهداف تجاريه وربحيه 
    اذا كان لأهداف تجاريه ، لا امانع المشاركه معهم وهم ايضا يشاركوني ربحهم 😃


كل ده أسباب وايضاً اقدم برنامج مجاني وامن تماما وخالي من اى سرقه  معلومات

أنا اعلم أن هدفك لدعم المشروع وانا اقدر ذلك

**Comment by ilyassesalama** [comment]
بخصوص المشكل، أنا أستخدم Windows 11 و PowerShell Terminal.

أما بالنسبة للسورس كود، فأنا أتفهم كل ما قلته، أتمنى أن يبقى البرنامج شغالا دائما، وسأبلغ عن أي مشكل أجده كما أفعل دائما. شكرا على مجهوداتك.

**Comment by abdelrahman30x** [comment]
انا لغيت الاعداد الخاص بتعطيل عكس الكلمات 
لم اجرب Windows 11 من قبل ,  لكن من الواضح انهم دعموا اللغة العربية في Terminal بعد اكثر من 35 عام  :))
البرنامج سوف يتعرف علي نوع windwos تلقائيا ويظهر الكلمات صحيحة بدون اي اعدادات 
##
![Screenshot 2022-12-06 200605](https://user-images.githubusercontent.com/52821000/205990289-10ee5eaf-da4e-4af6-819b-f7a9d9731abb.jpg)
