### ISSUE TITLE
anime start with the last episode

### ISSUE THREAD

**Issue by 1amir-talaat** [abdulrahmanMostafa30/EgyBestBot#19]
when I download an anime the download start with the last episode not from first

**Comment by abdelrahman30x** [comment]
Nice, update to 1.28

**Comment by abdelrahman30x** [comment]
I uploaded update and delete because had a problem too

Egybest, in normal episodes, starts from the last to  first episode

But in anime, it is different, starting from the beginning to ending

but last season in anime, starts from the last to  first episode 😕 lol

Anway, i fixed 1.28
