### ISSUE TITLE
Folder name sanitation

### ISSUE THREAD

**Issue by mostafa-abdelbrr** [abdulrahmanMostafa30/EgyBestBot#2]
# Issue:
When the movie or show name has any invalid characters like `:` in `Batman: The Animated Series` the program will either fail or use the last used folder (if any other valid series or movie was already downloaded).

# For a list of invalid characters:
https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names

# Suggested fix:
Simple search and replace/remove before making folder.

**Comment by abdelrahman30x** [comment]
Thanks for reporting the issue,
Fixed in [1.1](https://github.com/abdulrahmanMostafa30/EgyBestBot/releases/tag/1.1) .
