### ISSUE TITLE
No module named PIL

### ISSUE THREAD

**Issue by CrcakOnDemand** [abdulrahmanMostafa30/EgyBestBot#4]
PS C:\Users\ok\AppData\Local\Programs\EgyBestBot> .\EgyBestBot.exe
Traceback (most recent call last):
  File "Main.py", line 7, in <module>
ModuleNotFoundError: No module named 'PIL'
[9416] Failed to execute script 'Main' due to unhandled exception!

**Comment by abdelrahman30x** [comment]
Uninstall the current version 1.3
Download version <a href="https://github.com/abdulrahmanMostafa30/EgyBestBot/releases/tag/1.4">1.4</a>  and install.
