### ISSUE TITLE
Downloading a movie

### ISSUE THREAD

**Issue by itsmo-ks** [abdulrahmanMostafa30/EgyBestBot#7]
![Capture](https://user-images.githubusercontent.com/62901183/188199430-37dcaa1e-d006-49d2-8956-5daaf8dfa7a5.PNG)

When I choose to download the movie to download folder , I get this error

**Comment by abdelrahman30x** [comment]
<p dir="auto">Try this: <a href="https://github.com/abdulrahmanMostafa30/EgyBestBot/releases/tag/1.7">1.7</a>

**Comment by itsmo-ks** [comment]
![Capture](https://user-images.githubusercontent.com/62901183/188207532-d7a3a1d7-259a-4c3c-b589-ddfdb7407ffc.PNG)

I have updated it , and now this when trying to download specific episodes from a serie
* in movies too now

**Comment by abdelrahman30x** [comment]
Usually this problem occurs when you try to download video a lot
I added 3 attempts, between each attempt 3 seconds, so the server can return the video
Retry download and install again <a href="https://github.com/abdulrahmanMostafa30/EgyBestBot/releases/tag/1.7">1.7</a>
Try and let me the result.

**Comment by itsmo-ks** [comment]
Same problem , using V1.7 , same problem as the screenshot above

**Comment by itsmo-ks** [comment]
![Capture](https://user-images.githubusercontent.com/62901183/188238763-981c8f74-b77d-4aaa-9e14-83840c823bc6.PNG)

-another error when trying to copy links to clipboard
-and when I save links to text it saves them to links.txt , it's better if it saves them to the (the name of the movie or the serie(number of the season and episodes included) , will be great if you can do that

**Comment by abdelrahman30x** [comment]
Save to txt : Some download programs like idm support importing a text file and extracting links from it
Instead of sending each link to idm 
But there is no problem, I added the episode information before the link
In both cases, idm will recognize the links 😅

Try downloading with same program and tell me the result 

New version <a href="https://github.com/abdulrahmanMostafa30/EgyBestBot/releases/tag/1.8">1.8</a> 👍

**Comment by itsmo-ks** [comment]
Do I need to Uninstall the version I have then installing the latest version,  or I just install it without Uninstalling the previous version like i do ?

**Comment by abdelrahman30x** [comment]
No need, but the program must be closed.

**Comment by itsmo-ks** [comment]
![Capture](https://user-images.githubusercontent.com/62901183/188287827-e4727543-fffe-4fba-ad00-32a88d4dceff.PNG)
 
When I choose to download the videos from the program itself , it skips the first videos and jump to the other ones , here in the pic I chose to download from episode 6 to 10 , and it starts from 8 and it skips 6 and 7

**Comment by abdelrahman30x** [comment]
Inshallah, this will be the last version without any problems 😂
<a href="https://github.com/abdulrahmanMostafa30/EgyBestBot/releases/tag/1.9">1.9</a>

**Comment by abdelrahman30x** [comment]
The problem is general because of the egybest server
The server was late in returning the file information. I made a large number of timeout. 😕

**Comment by itsmo-ks** [comment]
Now it's working perfectly , even it's takes so much time to download link by link , but it's good now.
I wanna ask , which library you're using for the download ?

**Comment by abdelrahman30x** [comment]
Using cURL in Python with PycURL.

**Comment by itsmo-ks** [comment]
It will be better if you use Aria2 , because it has better download speed and it can download from a text file , means it can support multiple downloads at once.
It's just a suggestion*

**Comment by abdelrahman30x** [comment]
Pycurl already in the program supports multi file downloads, multi threading
It splits the video into 16 files and downloads them at the same time

It is not available automatically in the library, but you can add it, the YouTube Video Tutorial i uploaded, there was no difference between downloading the program itself or idm so there was no difference if it was aria2c

![](https://media.giphy.com/media/5nZpv1NyRQGDYp6ior/giphy.gif)


If you mean to download the episodes together?
I can't display more than one download episode at the same time from the console.
It will better to download an episode by episode

**Comment by itsmo-ks** [comment]
Thanks for explanation, I appreciate what you're doing , and thank you again for making that great program

**Comment by abdelrahman30x** [comment]
It was the least I could do 🖤
