### ISSUE TITLE
problem need to fix

### ISSUE THREAD

**Issue by EL-M3ndy** [abdulrahmanMostafa30/EgyBestBot#9]
Dear Abdo, let me first thank you for the bot that you made. It is great and very much effort. A very good effort and a very good result. It seems that the bot worked very well at first, but in the last update, I found a problem: the download box for the series or movies did not appear, as shown in the picture. As a precaution, I wanted you to be aware of this problem. Thank you. We hope to see a lot of programs for you. You are doing a really good job.

link picture: https://ibb.co/d7NJp3J

**Comment by abdelrahman30x** [comment]
Glad to help 😅🖤
I add new update <a href="https://github.com/abdulrahmanMostafa30/EgyBestBot/releases/tag/1.10">1.10</a>
I think the problem you have is related to the vpn, but i'm not sure
In update 1.10, I added message if you are used vpn or Egybest not available in your country
Update, and tell me result.
<br>

> ![image](https://user-images.githubusercontent.com/52821000/189453919-8110b8ab-40fd-43bc-95b4-3a70e5633c2b.png)

**Comment by EL-M3ndy** [comment]
Thank you for contacting me, Abdo. I don't use VPN, I live in Egypt, I reinstalled the program, but the problem is still there, when I used the URL, I put a link to a movie from the EGYBEST site and was able to download it - it's only the search that's not working.
![2022-09-10_133210](https://user-images.githubusercontent.com/113075763/189459534-7e0d8656-e432-4725-bade-4bac435f9822.png)

**Comment by abdelrahman30x** [comment]
go to file C:\Users\username\AppData\Local\EgyBestBot\config.ini
replace username for you with your username windwos
last_url_egybest  is url has redirected from https://www.egy.best/
tell me what last_url_egybest  in your file 

![image](https://user-images.githubusercontent.com/52821000/189461429-94d64efd-4950-4aa7-b2ab-6f3ff84592bc.png)

**Comment by EL-M3ndy** [comment]
I followed your instructions and this is what appeared. Is there anything wrong?
![2022-09-10_145541](https://user-images.githubusercontent.com/113075763/189462711-9a068dba-975e-4ed6-94d9-00f2b829478f.png)

**Comment by abdelrahman30x** [comment]
open https://www.egy.best/ from browser with incognito mode and tell me if egybest work and what url redirected ?

**Comment by abdelrahman30x** [comment]
![egybestbot](https://user-images.githubusercontent.com/52821000/189463119-401ce3ea-25a7-4bd9-8b7a-3c518e07678b.gif)

**Comment by EL-M3ndy** [comment]
I am sorry for my late
![2022-09-10_151946](https://user-images.githubusercontent.com/113075763/189463328-8ed4ab1e-7dd4-4908-a4d0-82260e50ecc0.png)

**Comment by abdelrahman30x** [comment]
give me autoComplete url from inspect 
![egybestbot](https://user-images.githubusercontent.com/52821000/189463904-e2c9af40-e1f1-4f5f-a70c-15dbd714626b.gif)

**Comment by EL-M3ndy** [comment]
Access denied Error code 1020
You cannot access www.egy.best. Refresh the page or contact the site owner to request access.

**Comment by EL-M3ndy** [comment]
Access denied Error code 1020
You cannot access www.egy.best. Refresh the page or contact the site owner to request access.
![2022-09-10_155105](https://user-images.githubusercontent.com/113075763/189464424-2997763a-5f9a-4b7c-a7ac-34c0bce2a5c2.png)

**Comment by abdelrahman30x** [comment]
This means that the search is not at working for you from site https://www.egy.best/ , right? 😅

**Comment by EL-M3ndy** [comment]
I don't understand where the problem is, as when I type in the search it just doesn't show any options
![Video_2022-09-10_160424](https://user-images.githubusercontent.com/113075763/189465026-896d7931-ac46-49a9-b23b-6107709bf04d.gif)

**Comment by EL-M3ndy** [comment]
But when I used this link https://feto.egybest.ninja/trending/ , I was able to get the code :
{"s":[{"t":"Spider-Man: No Way Home (2021)","u":"movie\/spider-man-no-way-home-2021","i":"c2NJbHBJYWNtbW1ibW12Tmptb1JjdndhY05FbXZhS1A"},{"t":"Stranger Things","u":"series\/stranger-things-2016","i":"c2NJbHBJYWNtYm1MY21wWWpFY3ZjdmNQYW1ibW1tbXZj"},{"t":"Squid Game","u":"series\/squid-game","i":"c2NJbHBJYWNtbW1ZYnZOWW1tbUVjeG16UGFtbW1yTno"},{"t":"The Shawshank Redemption (1994)","u":"movie\/the-shawshank-redemption-1994","i":"c2NJbHBJYWNtRW1qbWJtYm1qRWN2Y3dUWWdheG1Idw"},{"t":"Shutter Island (2010)","u":"movie\/shutter-island-2010","i":"c2NJbHBJYWNtVG1tVEVtbW1ZYkVjbWJ2Y2FtVHBoTGM"},{"t":"Star Wars: The Force Awakens (2015)","u":"movie\/star-wars-episode-vii-the-force-awakens-2015","i":"c2NJbHBJYWNtVG1tcEhOdWNja05UWVR2dmNtag"}]}

**Comment by abdelrahman30x** [comment]
Try this update <a href="https://github.com/abdulrahmanMostafa30/EgyBestBot/releases/tag/1.11">1.11</a>
It will fix the problem , If autoComplete not work , the program will search by pages 

![image](https://user-images.githubusercontent.com/52821000/189496012-6291b681-f381-45d0-9908-d2bd843a0648.png)

**Comment by EL-M3ndy** [comment]
Yes, bro, the search is working now❤😁. Thank you so much for this effort and throughout your career, I wish you all the best. keep moving
![2022-09-11_143628](https://user-images.githubusercontent.com/113075763/189506558-5e3cb55c-15bc-415a-9a55-64aea5afe816.png)
